sudo: required
services:
    - docker

before_install:
    - docker build -t ashar/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true ashar/react-test npm run test

after_success:
    - docker build -t asharanees/multi-client ./client
    - docker build -t asharanees/multi-nginx ./nginx
    - docker build -t asharanees/multi-server ./server
    - docker build -t asharanees/multi-worker ./worker
    - echo "$Docker_Password"| docker login -u "$Docker_ID" --password-stdin
    - docker push asharanees/multi-client
    - docker push asharanees/multi-nginx
    - docker push asharanees/multi-server
    - docker push asharanees/multi-worker